fragment PagesParts on Pages {
  __typename
  title
  subtitle
  body
}

fragment VsPageParts on VsPage {
  __typename
  heroHeading
  heroSubtext
  sectionLabel
  sectionHeading
  sectionSubtext
  ctaHeading
  ctaSubtext
  comparisonBlocks {
    __typename
    heading
    body
    bullets
    visualTitle
    visualDesc
  }
  featureTable1 {
    __typename
    label
    heading
    subtext
    col2
    col3
    rows {
      __typename
      feature
      glucose
      col2
      col3
    }
  }
  featureTable2 {
    __typename
    label
    heading
    subtext
    col2
    col3
    rows {
      __typename
      feature
      glucose
      col2
      col3
    }
  }
  engagementStack {
    __typename
    heading
    legacyLabel
    legacyItems
    agenticLabel
    agenticItems
  }
  testimonials {
    __typename
    label
    heading
    subtext
    items {
      __typename
      quote
      name
      role
      avatarSrc
      avatarAlt
    }
  }
  pricingLabel
  pricingHeading
  pricingSubtext
}

fragment CustomersPageParts on CustomersPage {
  __typename
  heroHeading
  heroSubtext
  ctaHeading
  ctaSubtext
  featuredCustomer {
    __typename
    heading
    body
    href
    imageSrc
    imageAlt
    logoSrc
    logoAlt
    metrics {
      __typename
      label
      value
    }
  }
  featuredTestimonial {
    __typename
    quote
    name
    role
    logoSrc
    logoAlt
    avatarSrc
    avatarAlt
  }
  results {
    __typename
    title
    industry
    href
    imageSrc
    imageAlt
    logoSrc
    logoAlt
    metrics {
      __typename
      label
      value
    }
  }
  successStories {
    __typename
    brand
    title
    body
    href
    imageSrc
    imageAlt
  }
}

fragment CompanyPageParts on CompanyPage {
  __typename
  heroLabel
  heroHeading
  heroSubtext
  heroImageSrc
  heroImageAlt
  missionHeading
  missionBody
  teamHeading
  teamSubtext
  visionLabel
  visionHeading
  statsLabel
  statsHeading
  statsSubtext
  globalPresenceHeading
  globalPresenceBody1
  globalPresenceBody2
  ctaHeading
  ctaSubtext
  teamMembers {
    __typename
    imageSrc
    name
    role
    bio
    linkedInHref
  }
  visionCards {
    __typename
    title
    body
  }
  values {
    __typename
    title
    body
    iconName
  }
  companyStats {
    __typename
    value
    label
  }
  offices {
    __typename
    name
    address
  }
}

fragment ContactPageParts on ContactPage {
  __typename
  heroHeading
  formHeading
  formSubtext
  trustedBrandsLabel
  trustedBrandsSubtext
  formAction
  formSubject
  formRedirectUrl
  demoFeatures
  industryOptions
}

fragment DemoPageParts on DemoPage {
  __typename
  heroLabel
  heroHeading
  heroSubtext
  ctaHeading
  ctaSubtext
  featureSections {
    __typename
    id
    industry
    reversed
    label
    heading
    tagline
    body
    linkText
    videoSrc
  }
}
